version: '3'
services:
    ngrok:
      image: wernight/ngrok:latest
      ports:
        - 4040:4040
      links:
        - backend
      environment:
        - NGROK_PORT=backend:5000
    backend:
        build: ./backend
        ports:
          - 5000:5000
        volumes:
            - ./storage:/app/storage
            - ./backend/src:/app/src:ro
    # frontend:
    #     build: ./frontend
    #     volumes:
    #         - ./frontend/src:/root/src:ro
