version: '3.7'
services:

    ngrok:
      image: wernight/ngrok:latest
      ports:
        - 4040:4040
      links:
        - backend
      environment:
        - NGROK_PORT=backend:5000
    backend:
        build: ./backend
        volumes:
            - ./storage:/root/storage
            - ./backend/src:/root/src:ro
    frontend:
        build: ./frontend
        volumes:
            - ./frontend/src:/root/src:ro
