version: 2
jobs:
  backend:
    docker:
      - image: python:3.7-alpine
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run: make lint
      - run: make build
      - run: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - backend